# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  "9router" = {
    pname = "9router";
    version = "v0.4.59";
    src = fetchFromGitHub {
      owner = "decolua";
      repo = "9router";
      rev = "v0.4.59";
      fetchSubmodules = false;
      sha256 = "sha256-O1JzMmH3ERpOv+HJw58s0EP1WNWGNAe709wX5APR6uc=";
    };
  };
  codegraph = {
    pname = "codegraph";
    version = "v0.9.3";
    src = fetchFromGitHub {
      owner = "colbymchenry";
      repo = "codegraph";
      rev = "v0.9.3";
      fetchSubmodules = false;
      sha256 = "sha256-EapQQKH+GTcNWw0c/nypCOtpuoAgXnBgCbEVfQrLoL8=";
    };
  };
  hanabi = {
    pname = "hanabi";
    version = "854f3a93665e9d09edb3f944a8bce8d368a2e17f";
    src = fetchFromGitHub {
      owner = "jeffshee";
      repo = "gnome-ext-hanabi";
      rev = "854f3a93665e9d09edb3f944a8bce8d368a2e17f";
      fetchSubmodules = false;
      sha256 = "sha256-+BrCMh6hDGNDVsReNoPzG3kNpnstjj0Cwdo/r2QIEkQ=";
    };
    date = "2026-05-22";
  };
  openhuman = {
    pname = "openhuman";
    version = "v0.54.0";
    src = fetchFromGitHub {
      owner = "tinyhumansai";
      repo = "openhuman";
      rev = "v0.54.0";
      fetchSubmodules = false;
      sha256 = "sha256-q8ZdTjpPWStkE0xD4Iy4FZDTC5DGuyviTCml7CdiiA8=";
    };
  };
  tlauncher = {
    pname = "tlauncher";
    version = "2.9319";
    src = fetchurl {
      url = "https://tlauncher.org/jar";
      sha256 = "sha256-xht2qWiXbOi6ezHziEcSVCxN6BPKDG8yQZSvULnLRW8=";
    };
  };
}
