# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  codegraph = {
    pname = "codegraph";
    version = "v0.9.9";
    src = fetchFromGitHub {
      owner = "colbymchenry";
      repo = "codegraph";
      rev = "v0.9.9";
      fetchSubmodules = false;
      sha256 = "sha256-Oy0WpllYQDmKpVhf+xI3Y18s+0x2bzkN8DDgTOJf4B4=";
    };
  };
  hanabi = {
    pname = "hanabi";
    version = "1ba3be9474555a1298fa5067e1f9d4fbe3901fbb";
    src = fetchFromGitHub {
      owner = "jeffshee";
      repo = "gnome-ext-hanabi";
      rev = "1ba3be9474555a1298fa5067e1f9d4fbe3901fbb";
      fetchSubmodules = false;
      sha256 = "sha256-/pLLg0J9QanaUjQl0iP6u0CxAeEDweTJYREs1XuhAsQ=";
    };
    date = "2026-06-07";
  };
  openhuman = {
    pname = "openhuman";
    version = "v0.57.18";
    src = fetchFromGitHub {
      owner = "tinyhumansai";
      repo = "openhuman";
      rev = "v0.57.18";
      fetchSubmodules = false;
      sha256 = "sha256-2uphqvAgPrBdgVIRKEwVH+7rNkgips3fvFePTzCA2K4=";
    };
  };
  pake = {
    pname = "pake";
    version = "V3.11.8";
    src = fetchFromGitHub {
      owner = "tw93";
      repo = "Pake";
      rev = "V3.11.8";
      fetchSubmodules = false;
      sha256 = "sha256-ftEdDZQ6io5DQtFkHijroXmPMa2s6ycVOIWEqTuvEeA=";
    };
  };
  tlauncher = {
    pname = "tlauncher";
    version = "2.9319";
    src = fetchurl {
      url = "https://tlauncher.org/jar";
      sha256 = "sha256-xht2qWiXbOi6ezHziEcSVCxN6BPKDG8yQZSvULnLRW8=";
    };
  };
  mcp-server-trello = {
    pname = "mcp-server-trello";
    version = "1.7.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@delorenj/mcp-server-trello/-/mcp-server-trello-1.7.1.tgz";
      sha256 = "sha256-JfjYy5CGJhtj5RCfMnrmFtqIXmPff9KbMl/0HPAj4l8=";
    };
  };
}
