[codegraph]
src.github = "colbymchenry/codegraph"
fetch.github = "colbymchenry/codegraph"
pinned = true

[hanabi]
src.git = "https://github.com/jeffshee/gnome-ext-hanabi.git"
fetch.github = "jeffshee/gnome-ext-hanabi"

[openhuman]
src.github = "tinyhumansai/openhuman"
fetch.github = "tinyhumansai/openhuman"
pinned = true

[pake]
src.github = "tw93/Pake"
fetch.github = "tw93/Pake"

[tlauncher]
src.webpage = "https://tlauncher.org/"
src.regex = 'TLauncher ([\d.]+)'
fetch.url = "https://tlauncher.org/jar"

[mcp-server-trello]
src.webpage = "https://registry.npmjs.org/@delorenj/mcp-server-trello/latest"
src.regex = '"version":"([^"]+)"'
fetch.url = "https://registry.npmjs.org/@delorenj/mcp-server-trello/-/mcp-server-trello-{{version}}.tgz"
