{ pkgs, inputs, ... }:

{
  imports = [
    # inputs.niri.homeModules.niri
    inputs.dms.homeModules.dank-material-shell
    inputs.dms-plugin-registry.modules.default
    inputs.danksearch.homeModules.dsearch
    ../../../home-manager/default.nix
  ];

  home = {
    username = "aka";
    homeDirectory = "/home/aka";
    stateVersion = "26.05";

    packages = with pkgs; [
      discord
      firefox
      codex
      gocryptfs
      rustic
      spotify
    ];
  };

  programs = {
    modern-utils.enable = true;
    password-store.enable = true;
    home-manager.enable = true;
    bash.enable = true;
    clamav.enable = true;
    gpg.enable = true;
    git.lfs.enable = true;
    tmux.enable = true;
    vscode-fzf.enable = true;
    vscode-fzf.dirs = [ "$HOME/Kode/workspaces" ];
    yt-dlp.enable = true;
    yt-dlp.downloader = "wget";
    yt-dlp.path = "${config.home.homeDirectory}/Videos/YouTube";
    git.settings.core.editor = "${pkgs.vscode}/bin/code --wait";

    dank-material-shell = {
      enable = true;

      # Core features
      enableSystemMonitoring = true; # System monitoring widgets (dgop)
      enableVPN = true; # VPN management widget
      enableDynamicTheming = true; # Wallpaper-based theming (matugen)
      enableAudioWavelength = true; # Audio visualizer (cava)
      enableCalendarEvents = true; # Calendar integration (khal)
      enableClipboardPaste = true; # Pasting items from the clipboard (wtype)

      systemd = {
        enable = true; # Systemd service for auto-start
        restartIfChanged = true; # Auto-restart dms.service when dank-material-shell changes
      };

      settings = {
        theme = "dark";
        dynamicTheming = true;
      };

      # session = {
      #   isLightMode = false;
      #   # Add any other session state settings here
      # };

      # clipboardSettings = {
      #   maxHistory = 25;
      #   maxEntrySize = 5242880;
      #   # autoClearDays = 1;
      #   clearAtStartup = false;
      #   disabled = false;
      #   disableHistory = false;
      #   disablePersist = true;
      # };

      plugins = {
        dankBatteryAlerts.enable = true;
        wallpaperCarousel.enable = true;
        dmsScreenshot.enable = true;
        liveChartSchedule.enable = true;
        tasks.enable = true;
        nextBootSelector.enable = true;
        keybindingCheatSheet.enable = true;
        quranWidget.enable = true;
        powerUsagePlugin.enable = true;
        screenRecorder.enable = true;
        # dankAudioVisualizer.enable = true;
        # cavaVisualizer.enable = true;
        discordVoice.enable = true;
        githubHeatmap.enable = true;
        # githubNotifier.enable = true;
        # mpvpaperWallpaper.enable = true;
        wallpaperShufflerPlugin.enable = true;
        linuxWallpaperEngine.enable = true;
        qcalCalendar.enable = true;
        animeCalendar.enable = true;
        dankObsidian.enable = true;
        codexBar.enable = true;
        prayerTimes.enable = true;
        displayOutput.enable = true;
        vscodeLauncher.enable = true;
        nixMonitor.enable = true;
        dankBitwarden.enable = true;
        musicLyrics.enable = true;
        dmsPass.enable = true;
        tailscale.enable = true;
        displayManager.enable = true;

        mediaPlayer = {
          enable = true;
          settings = {
            preferredSource = "spotify";
          };
        };
      };

      # nixos module
      # niri = {
      # enableKeybinds = true; # Sets static preset keybinds
      # enableSpawn = true; # Auto-start DMS with niri, if enabled

      # includes = {
      #   enable = true; # Enable config includes hack. Enabled by default.
      #   override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      #   originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
      #   filesToInclude = [
      #     # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
      #     "alttab" # Please note that niri will throw an error if any of these files are missing.
      #     "binds"
      #     "colors"
      #     "layout"
      #     "outputs"
      #     "wpblur"
      #   ];
      # };
      # };
    };

    # TODO: test
    dsearch.enable = true;
  };
}
