name: Test
on: [ push ]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            profile: [ mint, manjaro ]
        steps:
            - uses: actions/checkout@v2
            - uses: cachix/install-nix-action@v12
              with:
                  nix_path: nixpkgs=channel:nixos-unstable
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - run: nix run nixpkgs#home-manager -- switch --show-trace --flake ${{ github.workspace }}#${{ matrix.profile }}